### ISSUE TITLE
Introductory Experiments : Not valid

### ISSUE THREAD

**Issue by rishi11** [chengchen886/CS5610-charlie#10]
The introductory experiments should be atleast "Hello World" Experiments.Hence, Experiments 1 and 2 will not be counted as experiments.

**Comment by chengchen886** [comment]
Ok, I will create another two mongoDB experiment after I solving my environment problem. Hope to see at TA hours.

Thanks,
Charlie

----- Original Message -----

**Comment by chengchen886** [comment]
Hi Rishi, I created another three connection to strings experiments to replace this two introductory experiments.
