### ISSUE TITLE
Week 8 : Experiments Missing

### ISSUE THREAD

**Issue by rishi11** [chengchen886/CS5610-charlie#12]
Please complete experiments for week 8

**Comment by chengchen886** [comment]
Hi Rishi,

I just completed the experiments for week 8, you can check in on my website below: 

http://net4.ccs.neu.edu/home/charlie

Could you help me to close this issue? Thanks and have a good night.

Thank you,
Charlie

----- Original Message -----

**Comment by rishi11** [comment]
Close the issue when you are done.
