### ISSUE TITLE
Week 10 : Experiments Missing

### ISSUE THREAD

**Issue by rishi11** [chengchen886/CS5610-charlie#14]
Please complete the experiments for Week 10.

Close the issues that you fixed, so that I will get a notification and check.

**Comment by chengchen886** [comment]
Thanks Rishi, I will upload my local experiment to the server soon. Good luck and have a nice day.

----- Original Message -----

**Comment by chengchen886** [comment]
Hi Rishi, I just complete the experiments for week 10.
