### ISSUE TITLE
Experiment Not Working

### ISSUE THREAD

**Issue by rishi11** [chengchen886/CS5610-charlie#3]
http://net4.ccs.neu.edu/home/charlie/experiments/week3/jquery001.html

This experiments seems to be non working.

**Comment by chengchen886** [comment]
Hi Rishi,

Could you specified it in detail which mistake I made? Thank you very much.

Cheng

----- Original Message -----

**Comment by rishi11** [comment]
Make you experiments more descriptive by adding documentation. Closing issue for now.
