### ISSUE TITLE
Non functional Experiment 

### ISSUE THREAD

**Issue by rishi11** [chengchen886/CS5610-charlie#4]
http://net4.ccs.neu.edu/home/charlie/experiments/week4/jquery003.html

No message is coming from jQuery.

**Comment by chengchen886** [comment]
Hi Rishi,

I just fixed it. 

Thanks,
Cheng

----- Original Message -----

**Comment by chengchen886** [comment]
Hi Rishi, I checked this link, the problem was resolved.
