### ISSUE TITLE
Documentation Not Proper.

### ISSUE THREAD

**Issue by rishi11** [chengchen886/CS5610-charlie#8]
Please provide proper documentation for this experiment : http://net4.ccs.neu.edu/home/charlie/experiments/week5/angularJS.html

File Utility Links Missing.

**Comment by chengchen886** [comment]
Hi Rishi,

I just changed the CSS file, the documentation is showing now.

----- Original Message -----

**Comment by rishi11** [comment]
Still not visible.

**Comment by chengchen886** [comment]
Hi Rishi,

Can you check it now, I updated it.  the scroll bar is showing, just scroll down the bar. Thanks.

Best,
cheng

----- Original Message -----

**Comment by chengchen886** [comment]
The purpose of this experiment is the name filer, when you type in the character in the column, the name not start from this character will disappear.

----- Original Message -----

**Comment by chengchen886** [comment]
Hi Rishi,

I will write down a new detail documentation and update it soon. Thanks for your patience.

Have a good night.

Best,
Cheng

----- Original Message -----

**Comment by chengchen886** [comment]
Hi Rishi,

I just checked this link, I had already fixed it.
