### ISSUE TITLE
Experiments Missing

### ISSUE THREAD

**Issue by rishi11** [chengchen886/CS5610-charlie#9]
This week you have performed only 3 experiments. The minimum number of experiments is 5. Please add two more experiments.

**Comment by chengchen886** [comment]
Hi Rishi,

I will update it tonight. Since I notice the poll in piazza and thought the experiments number changed.

Thanks

----- Original Message -----

**Comment by chengchen886** [comment]
Hi Rishi, I added two more experiments after you emailed me.
